from .enrollment_class import *
from .exam import *
from .exam_stage_subject_mapping import *
from .exam_subject_score import *
from .exam_type import *
from .grade_semester import *
from .school import *
from .school_stage_mapping import *
from .sgp_exam_subject_mapping import *
from .sgp_score import *
from .stage import *
from .stage_subject_mapping import *
from .student import *
from .student_enrollment_class_mapping import *
from .subject import *
from .teacher import *
from .teacher_subject_enrollment_class_mapping import *