# Generated by Django 5.1.1 on 2024-10-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgp_score',
            name='sgp_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='sgp成绩'),
        ),
    ]
