# Generated by Django 5.1.1 on 2024-10-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SgpScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu title')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu title')),
                ('des', models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu title')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Left icon')),
            ],
            options={
                'verbose_name': 'Sgp Score',
                'verbose_name_plural': 'Sgp Score',
            },
        ),
    ]
